'use client'
import {useState} from 'react'
import {motion} from 'framer-motion'
import {Canvas} from '@react-three/fiber'
import {Environment,OrbitControls} from '@react-three/drei'
import TransmissionModel from './TransmissionModel'

const parts=[
 ['PUMP & STATOR SUPPORT','Front pump, pump body and stator support at the converter end.'],
 ['1-2-3-4 / 3-5-R DRUM','Large front rotating drum carrying both major clutch systems.'],
 ['4-5-6 CLUTCH ASSEMBLY','Upper-range clutch drum, hub and friction stack.'],
 ['CENTER SUPPORT / 2-6 CLUTCH','Stationary center support and 2-6 clutch section.'],
 ['LOW / REVERSE CLUTCH','Stationary holding clutch nested around the rear geartrain.'],
 ['REAR PLANETARY / OUTPUT','Planet carrier, ring/sun members and output shaft.'],
 ['VALVE BODY','Wide cast hydraulic control body mounted directly above the pan.'],
 ['TEHCM / SOLENOID BODY','Integrated controller, solenoids and pressure-switch electronics.'],
]
export default function Home(){const[exploded,setExploded]=useState(false),[active,setActive]=useState(0);return <main>
<nav><a className="brand" href="#top"><b>TRANS-FORMERS</b><small>TRANSMISSION & COMPLETE AUTO REPAIR</small></a><div className="links"><a href="#services">SERVICES</a><a href="#lab">6L80 LAB</a><a href="#contact">CONTACT</a></div><a className="call" href="tel:+17065292706">CALL (706) 529-2706</a></nav>
<section id="top" className="photoHero"><div className="heroBackdrop"><img src="/shop-front-real.jpg" alt=""/></div><div className="heroShade"/><motion.div className="heroCopy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><p className="eyebrow">DALTON, GEORGIA • FAMILY OWNED</p><h1>BUILT.<br/><i>REBUILT.</i><br/>BACK ON THE ROAD.</h1><p className="sub">Transmission rebuilding, diagnostics and complete auto repair for all makes and models.</p><div className="actions"><a href="#services" className="primary">OUR SERVICES</a><a href="#lab" className="secondary">OPEN 6L80 LAB →</a></div></motion.div><motion.div className="heroVisual" initial={{opacity:0,scale:.97,y:18}} animate={{opacity:1,scale:1,y:0}}><div className="heroPhotoFrame"><img className="heroPhoto" src="/shop-front-real.jpg" alt="Front of Trans-Formers Transmission on Shugart Road in Dalton, Georgia"/></div><div className="realPhotoTag"><b>THE DALTON SHOP</b><span>844 SHUGART RD</span></div></motion.div></section>
<section className="stats"><div><b>TRANSMISSIONS</b><span>REBUILD • REPAIR • DIAGNOSE</span></div><div><b>ALL MAKES</b><span>DOMESTIC • IMPORT</span></div><div><b>IN-HOUSE</b><span>DIAGNOSIS & REBUILDING</span></div><div><b>DALTON</b><span>GEORGIA</span></div></section>
<section id="lab" className="lab"><div className="labHeading"><p className="eyebrow">INTERACTIVE 6L80 RECONSTRUCTION</p><h2>SEE WHAT'S<br/><i>INSIDE.</i></h2><p className="lead">A stylized but mechanically grounded 6L80 built for the web from teardown order and component relationships. The bellhousing, stepped case, black pan, extension housing, clutch assemblies, stationary support, rear planetary, valve body and TEHCM are separate interactive pieces.</p><button className="explodeButton" onClick={()=>setExploded(v=>!v)}>{exploded?'ASSEMBLE TRANSMISSION':'EXPLODE TRANSMISSION'}</button></div><div className="labStage"><Canvas camera={{position:[.25,2.8,9.8],fov:38}} dpr={[1,1.5]}><ambientLight intensity={.78}/><directionalLight position={[4,7,5]} intensity={2.15}/><directionalLight position={[-4,2,-3]} intensity={1.05}/><TransmissionModel exploded={exploded} active={active} pick={setActive}/><Environment preset="warehouse"/><OrbitControls enablePan={false} enableDamping minDistance={6.3} maxDistance={13.5}/></Canvas><div className="labHud"><span>DRAG TO ROTATE</span><span>PINCH / SCROLL TO ZOOM</span><strong>{exploded?'EXPLODED VIEW':'ASSEMBLED VIEW'}</strong></div></div><div className="componentPanel">{parts.map((p,i)=><button key={p[0]} className={active===i?'active':''} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,'0')}</span><b>{p[0]}</b><i>VIEW</i></button>)}</div><div className="partDetail"><span>SELECTED ASSEMBLY</span><h3>{parts[active][0]}</h3><p>{parts[active][1]}</p><div className="detailNote">The model is an original visual approximation, not GM factory CAD. It is intentionally simplified enough to stay smooth on phones while preserving the recognizable 6L80 layout.</div></div></section>
<section id="services" className="services"><div><p className="eyebrow">WHAT WE DO</p><h2>KEEP IT<br/><i>MOVING.</i></h2><p className="lead">Transmission diagnosis and rebuilding are the core, with complete auto repair available in the same shop.</p></div><div className="serviceList"><p><b>01</b> Transmission diagnosis</p><p><b>02</b> Transmission rebuilding & repair</p><p><b>03</b> General automotive repair</p><p><b>04</b> Maintenance & inspections</p><p><b>05</b> Electrical & drivability diagnosis</p></div></section>
<footer id="contact"><h2>GET YOUR VEHICLE<br/><i>BACK ON THE ROAD.</i></h2><p>844 Shugart Rd, Dalton, GA 30720 • (706) 529-2706</p><div className="footerActions"><a href="tel:+17065292706">CALL THE SHOP</a></div></footer></main>}